# Generated by Django 4.2.16 on 2024-10-08 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=25, verbose_name='Papka nomeri')),
                ('name', models.CharField(max_length=500, verbose_name='Papka nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Papka kiritilgan vaqti')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Papka',
                'verbose_name_plural': 'Papakalar',
            },
        ),
    ]
