# Generated by Django 4.2.16 on 2024-10-09 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_folders'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hujjat turi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
            ],
            options={
                'verbose_name': 'Hujjat turi',
                'verbose_name_plural': 'Hujjat turlari',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_code', models.CharField(max_length=20, verbose_name='Fayil kodi')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d', verbose_name='Fayil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.documenttype', verbose_name='Hujjat turi')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.folders', verbose_name='Papka')),
            ],
            options={
                'verbose_name': 'Fayil',
                'verbose_name_plural': 'Fayillar',
            },
        ),
    ]
