# Generated by Django 4.2.16 on 2024-10-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_documenttype_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='calendar',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hujjat sanasi'),
        ),
    ]
