# Generated by Django 4.2.16 on 2024-10-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_doc_type_alter_folders_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='doc_type',
        ),
    ]
