# Generated by Django 4.2.16 on 2024-10-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_category_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='doc_type',
            field=models.BooleanField(default=False, verbose_name='Hujjat turi'),
        ),
    ]
